# Dependencies
markdown: 		kramdown
kramdown:
  input: 		GFM
  syntax_highlighter: 	rouge

# Permalinks
permalink:           /posts/:title/

# Setup
title:            "Adrian Borucki's Blog"
tagline:          'Reflections on technology, society, etc.'
description:      'Reflections on technology, society, etc.'
url:              https://danlupei.github.io
baseurl:          ''
paginate:         5
#excerpt_separator: "<br>"
#gems:
#- jekyll-mentions
#- jemoji
#- jekyll-redirect-from
#- jekyll-sitemap
#- jekyll-feed

author:
  name:           'Adrian Borucki'
  url:            https://danlupei.github.io

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/danlupei/danlupei.github.io

disqusShortName:      danlupei
twitterAccountName:   la_danpei
#facebookDevAppId:
#googleAnalyticsSuperProxyQuery:
