# Dependencies
markdown:         kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        /posts/:title/

# Setup
title:            Adrian Borucki's Blog
tagline:          ""
description:      'Reflections on technology, society, etc.'
url:              http://danlupei.github.io
baseurl:          '/'
paginate:         3
excerpt_separator: "<br>"
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

author:
  name:           'Adrian Borucki'
  url:            http://danlupei.github.io

# Custom vars
version:          1.3.0

github:
  repo:           https://github.com/danlupei/danlupei.github.io

disqusShortName:     danlupei
twitterAccountName:   la_danpei
#facebookDevAppId:
#googleAnalyticsSuperProxyQuery:
