title: A blog of Adrian Borucki
email: gentoolx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Reflections on technology, society, self and others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://danlupei.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: la_danpei
github_username:  danlupei
theme: jekyll-theme-midnight

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
